esphome:
  name: stazione-aria-completa
  friendly_name: "Minirack Sensor"

esp8266:
  board: nodemcuv2

logger:
  level: DEBUG
  baud_rate: 115200

web_server:
  port: 80

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Air-Setup"
    password: "setup_password"

i2c:
  sda: D1
  scl: D2
  scan: true
  id: bus_a

uart:
  - id: uart_pm1006
    tx_pin: D6
    rx_pin: D5
    baud_rate: 9600

  - id: uart_ld2410
    tx_pin: D0
    rx_pin: D7
    baud_rate: 38400
    parity: NONE
    stop_bits: 1

ld2410:
  uart_id: uart_ld2410

sensor:
  - platform: aht10
    variant: AHT20
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      id: temp_aht
      filters:
        - offset: -4.0 # adjustment for calibration
    humidity:
      name: "Humidity"
      id: hum_aht
    update_interval: 60s

  - platform: ens160_i2c
    i2c_id: bus_a
    address: 0x53
    eco2:
      name: "Equivalent CO2"
    tvoc:
      name: "TVOC"
    aqi:
      name: "Air Quality Index"
    compensation:
      temperature: temp_aht
      humidity: hum_aht
    update_interval: 60s

  - platform: pm1006
    uart_id: uart_pm1006
    pm_2_5:
      name: "PM2.5"
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
    update_interval: 30s

  - platform: ld2410
    moving_distance:
      name: "Moving Distance"
    still_distance:
      name: "Still Distance"

binary_sensor:
  - platform: ld2410
    has_target:
      name: "Presence Detected"
    has_moving_target:
      name: "Motion Detected"
    has_still_target:
      name: "Still Target Detected"

switch:
  - platform: ld2410
    bluetooth:
      name: "Radar Bluetooth"